project_id = "bqtftgafybfawmmyvkaf"

[functions.send-email]
verify_jwt = true

[functions.process-email-reminders]
verify_jwt = true

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.analyze-nameplate]
verify_jwt = true
[functions.send-entretien-reminders]
verify_jwt = true
