import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import ClientCombobox from "@/components/forms/ClientCombobox";
import { toast } from "sonner";

interface Props { open: boolean; onOpenChange: (open: boolean) => void; order: any; onSaved: () => void; }
export default function EditOrderDialog({ open, onOpenChange, order, onSaved }: Props) {
  const [loading, setLoading] = useState(false); const [clients, setClients] = useState<any[]>([]); const [tasks, setTasks] = useState<any[]>([]);
  const [form, setForm] = useState({ part_name: "", part_reference: "", quantity: 1, supplier: "", urgency: "normal", client_id: "", work_task_id: "", notes: "" });
  useEffect(() => { if (!open || !order) return; setForm({ part_name: order.part_name || "", part_reference: order.part_reference || "", quantity: order.quantity || 1, supplier: order.supplier || "", urgency: order.urgency || "normal", client_id: order.client_id || "", work_task_id: order.work_task_id || "", notes: order.notes || "" }); supabase.from("clients").select("id, name, address_intervention").order("name").then(({ data }) => setClients(data ?? [])); supabase.from("work_tasks").select("id, title, scheduled_date, client_id").order("scheduled_date", { ascending: false }).limit(300).then(({ data }) => setTasks(data ?? [])); }, [open, order]);
  const set = (key: string, value: any) => setForm((f) => ({ ...f, [key]: value }));
  const selectClient = (clientId: string) => setForm((f) => ({ ...f, client_id: clientId, work_task_id: tasks.some((t) => t.id === f.work_task_id && t.client_id === clientId) ? f.work_task_id : "" }));
  const selectTask = (taskId: string) => { const task = tasks.find((t) => t.id === taskId); setForm((f) => ({ ...f, work_task_id: taskId, client_id: task?.client_id ?? f.client_id })); };
  const handleSubmit = async () => { if (!form.part_name.trim()) { toast.error("Le nom de la pièce est obligatoire"); return; } if (!form.work_task_id) { toast.error("Sélectionnez la tâche liée"); return; } setLoading(true); const { error } = await supabase.from("parts_orders").update({ part_name: form.part_name.trim(), part_reference: form.part_reference || null, quantity: form.quantity, supplier: form.supplier || null, urgency: form.urgency as any, client_id: form.client_id || null, work_task_id: form.work_task_id, notes: form.notes || null }).eq("id", order.id); setLoading(false); if (error) toast.error("Erreur : " + error.message); else { toast.success("Commande modifiée"); onOpenChange(false); onSaved(); } };
  const visibleTasks = form.client_id ? tasks.filter((t) => t.client_id === form.client_id) : tasks;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Modifier la commande</DialogTitle><DialogDescription>Modifiez les informations de la demande de pièce.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Nom de la pièce *</Label><Input value={form.part_name} onChange={(e) => set("part_name", e.target.value)} /></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Référence</Label><Input value={form.part_reference} onChange={(e) => set("part_reference", e.target.value)} /></div><div className="space-y-2"><Label>Quantité</Label><Input type="number" min={1} value={form.quantity} onChange={(e) => set("quantity", parseInt(e.target.value) || 1)} /></div></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Fournisseur</Label><Input value={form.supplier} onChange={(e) => set("supplier", e.target.value)} /></div><div className="space-y-2"><Label>Urgence</Label><Select value={form.urgency} onValueChange={(v) => set("urgency", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="normal">Normal</SelectItem><SelectItem value="urgent">Urgent</SelectItem><SelectItem value="critique">Critique</SelectItem></SelectContent></Select></div></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Client</Label><ClientCombobox clients={clients} value={form.client_id} onChange={selectClient} placeholder="Rechercher un client..." /></div><div className="space-y-2"><Label>Tâche liée *</Label><Select value={form.work_task_id} onValueChange={selectTask}><SelectTrigger><SelectValue placeholder="Sélectionner" /></SelectTrigger><SelectContent className="max-h-64">{visibleTasks.map((t) => <SelectItem key={t.id} value={t.id}>{t.scheduled_date?.split("-").reverse().join("/")} · {t.title}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label>Notes</Label><Textarea value={form.notes} onChange={(e) => set("notes", e.target.value)} rows={3} /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button onClick={handleSubmit} disabled={loading}>{loading ? "Enregistrement..." : "Enregistrer"}</Button></DialogFooter></DialogContent></Dialog>;
}
