ALTER TABLE public.work_tasks REPLICA IDENTITY FULL;
ALTER TABLE public.intervention_sheets REPLICA IDENTITY FULL;
ALTER TABLE public.parts_orders REPLICA IDENTITY FULL;
ALTER TABLE public.quotes REPLICA IDENTITY FULL;